[versions]
org-slf4j-slf4j-api = "2.0.17"
org-slf4j-slf4j-simple = "2.0.17"

[libraries]
org-slf4j-slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "org-slf4j-slf4j-api" }
org-slf4j-slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "org-slf4j-slf4j-simple" }
